name: Deploy to EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Check out the repository code
    - uses: actions/checkout@v2

    # Copy files to EC2
    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/ec2-user/devopsca"
        exclude: "node_modules,.git"

    # Execute deploy.sh script on EC2
    - name: Execute deploy.sh script on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/devopsca
          export ENV=DEV
          chmod +x deploy.sh
          bash deploy.sh